server:
  port: 7171

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?current_schema=order_db
    username: temporal
    password: temporal
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        hbm2ddl:
          create_namespaces=true
    sql:
      init:
        mode: always

