version: '3.8'
services:
  elasticsearch:
    container_name: temporal-elasticsearch
    environment:
      - cluster.routing.allocation.disk.threshold_enabled=true
      - cluster.routing.allocation.disk.watermark.low=512mb
      - cluster.routing.allocation.disk.watermark.high=256mb
      - cluster.routing.allocation.disk.watermark.flood_stage=128mb
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms256m -Xmx256m
      - xpack.security.enabled=false
    image: elasticsearch:9.1.4
    networks:
      - temporal-network
    expose:
      - 9200
    volumes:
      - /var/lib/elasticsearch/data
  postgres12:
    container_name: temporal-postgresql
    environment:
      POSTGRES_PASSWORD: temporal
      POSTGRES_USER: temporal
    image: postgres:13.1
    networks:
      - temporal-network
    ports:
      - 5432:5432
    expose:
      - 5433
      - 5432
    volumes:
      - /var/lib/postgresql/data

  temporal:
    container_name: temporal
    depends_on:
      - postgres12
      - elasticsearch
    environment:
      - DB=postgres12
      - DB_PORT=5433
      - POSTGRES_USER=temporal
      - POSTGRES_PWD=temporal
      - POSTGRES_SEEDS=postgres12
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development-sql.yaml
      - ENABLE_ES=true
      - ES_SEEDS=elasticsearch
      - ES_VERSION=v7
    image: temporalio/auto-setup:1.26.3.0
    networks:
      - temporal-network
    ports:
      - 7233:7233
    labels:
      kompose.volume.type: configMap
    volumes:
      - ./dynamicconfig:/etc/temporal/config/dynamicconfig

  temporal-admin-tools:
    container_name: temporal-admin-tools
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CLI_ADDRESS=temporal:7233
    image: temporalio/admin-tools:1.28.1-tctl-1.18.4-cli-1.4.1
    networks:
      - temporal-network
    stdin_open: true
    tty: true
  temporal-ui:
      container_name: temporal-ui
      depends_on:
        - temporal
      environment:
        - TEMPORAL_ADDRESS=localhost:7233
        - TEMPORAL_CORS_ORIGINS=http://localhost:3000,http://localhost:7080,http://localhost:8080
      image: temporalio/ui:2.40.1
      networks:
        - temporal-network
      ports:
        - 8080:8080

networks:
  temporal-network:
    driver: bridge
    name: temporal-network
